# Generated by Django 4.2.1 on 2023-05-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_board_todo_created_at_todo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
